plugins:
  # https://github.com/jest-community/eslint-plugin-jest
  - jest
  - fp

env:
  node: true

extends:
  - airbnb-base
  - 'plugin:jest/recommended'

parserOptions:
  ecmaVersion: latest
  sourceType: module
rules:
  no-console: 0
  import/extensions: 0
  fp/no-let: 'error'
  fp/no-mutation: 'error'
  fp/no-mutating-methods: 'error'
